on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akstest2acr.azurecr.io
        username: ${{ secrets.acr_akstest2acr_username }}
        password: ${{ secrets.acr_akstest2acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akstest2acr.azurecr.io/vipulakscluster:${{ github.sha }}
        docker push akstest2acr.azurecr.io/vipulakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vipulakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vipulaksclustereebb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vipulaksclustereebb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vipulaksclustereebb
        container-registry-url: akstest2acr.azurecr.io
        container-registry-username: ${{ secrets.acr_akstest2acr_username }}
        container-registry-password: ${{ secrets.acr_akstest2acr_password }}
        secret-name: vipulaksclusdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: chart/hello/
        releaseName: akstest2acr.azurecr.io/vipulakscluster
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository: akstest2acr.azurecr.io/vipulakscluster
          image.tag:${{ github.sha }}
          image.pullSecret:vipulaksclusdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1
      with:
        namespace: vipulaksclustereebb
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          akstest2acr.azurecr.io/vipulakscluster:${{ github.sha }}
        imagepullsecrets: |
          vipulaksclusdockerauth
